In [1]:
import numpy as np
from scipy.linalg import norm
# np.set_printoptions(precision=2)

In [2]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])

In [3]:
U, d, V_t = np.linalg.svd(A)
V = V_t.T
D = np.zeros_like(A, dtype=float)
for i in range(min(A.shape)):
    D[i][i] = d[i]

In [4]:
print(f'Матрица A:\n{A}\n')
print('*'*100)
print(f'Матрица U:\n{U}\n')
print(f'Матрица V:\n{V}\n')
print(f'Матрица D:\n{D}]\n')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]

****************************************************************************************************
Матрица U:
[[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]

Матрица V:
[[ 0.07116451 -0.36737824 -0.92734505]
 [ 0.71702467  0.66514082 -0.20847855]
 [ 0.69340553 -0.65009301  0.31075368]]

Матрица D:
[[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]]



In [5]:
A = np.dot(U, np.dot(D, V.T))
print('*'*100)
print(f'Матрица A:\n{np.round(A)}\n')

****************************************************************************************************
Матрица A:
[[ 1.  2. -0.]
 [-0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1. -0.]]



Для матрицы из предыдущего задания найти с помощью NumPy и вручную:

а) Евклидову норму;

In [7]:
np.linalg.norm(A, ord=2)

8.82486885482045

In [8]:
norm(A, ord=2)

8.82486885482045

б) норму Фробениуса.

In [9]:
sum_a = 0
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        sum_a += (A[i][j])**2
result = sum_a**0.5
print(result)

11.045361017187263


In [10]:
np.linalg.norm(A)

11.045361017187265