In [11]:
import numpy as np
import scipy.linalg

In [2]:
# К задаче 2а (часть 1)
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
A_ex = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
rank_A = np.linalg.matrix_rank(A)
rank_A_ex = np.linalg.matrix_rank(A_ex)
print(f'ранг матрицы А: {rank_A}',
      f'ранг расширенной матрицы А: {rank_A_ex}', sep='\n')

ранг матрицы А: 3
ранг расширенной матрицы А: 3


In [3]:
# К задаче 2б (часть 1)
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
A_ex = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])
rank_A = np.linalg.matrix_rank(A)
rank_A_ex = np.linalg.matrix_rank(A_ex)
print(f'ранг матрицы А: {rank_A}',
      f'ранг расширенной матрицы А: {rank_A_ex}', sep='\n')

ранг матрицы А: 1
ранг расширенной матрицы А: 2


In [4]:
# К задаче 2в (часть 1)
A = np.array([[1, 2, 5], [3, 1, -8]])
A_ex = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
rank_A = np.linalg.matrix_rank(A)
rank_A_ex = np.linalg.matrix_rank(A_ex)
print(f'ранг матрицы А: {rank_A}',
      f'ранг расширенной матрицы А: {rank_A_ex}', sep='\n')

ранг матрицы А: 2
ранг расширенной матрицы А: 2


In [7]:
# К задаче 3(часть 1)
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
A_ex = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2],
                 [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
rank_A = np.linalg.matrix_rank(A)
rank_A_ex = np.linalg.matrix_rank(A_ex)
print(f'ранг матрицы А: {rank_A}',
      f'ранг расширенной матрицы А: {rank_A_ex}', sep='\n')

ранг матрицы А: 4
ранг расширенной матрицы А: 4


****************************************************************************************************************************
# ЧАСТЬ 2

In [10]:
# задача 1 б) - часть 2
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
A_1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
A_2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
A_3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])

detA = round(np.linalg.det(A))
detA_1 = round(np.linalg.det(A_1))
detA_2 = round(np.linalg.det(A_2))
detA_3 = round(np.linalg.det(A_3))

x_1 = round(detA_1/detA)
x_2 = round(detA_2/detA)
x_3 = round(detA_3/detA)

print(f'определитель матрицы А: {detA}')
print(f'определитель матрицы А_1: {detA_1}, x_1 = {x_1}')
print(f'определитель матрицы А_2: {detA_2}, x_2 = {x_2}')
print(f'определитель матрицы А_3: {detA_3}, x_3 = {x_3}')

определитель матрицы А: 43
определитель матрицы А_1: 86, x_1 = 2
определитель матрицы А_2: -43, x_2 = -1
определитель матрицы А_3: 43, x_3 = 1


In [15]:
# к задаче 2 а
# из-за особенностей алгоритма расчета в python (выбора ведущих элементов)
# результаты формирования матрицы LU могут не совпадать с тем, что в pdf
# и собсвенно не совпадают

A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
lu, p = scipy.linalg.lu_factor(A)
print(lu, p, sep='\n\n')

[[ 3.         26.         30.        ]
 [ 0.66666667 -8.33333333 -8.        ]
 [ 0.33333333  0.8         0.4       ]]

[2 1 2]


In [16]:
# к задаче 2 б

A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
lu, p = scipy.linalg.lu_factor(A)
print(lu, p, sep='\n\n')

[[  4.          22.          53.          33.        ]
 [  0.5         -6.         -18.5         -7.5       ]
 [  0.75        -0.25       -15.375       -8.625     ]
 [  0.25         0.75        -0.17073171  -0.09756098]]

[3 1 2 3]


In [22]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])
lu, p = scipy.linalg.lu_factor(A)
print(f'матрица LU:\n{lu}', f'pivot: {p}\n', sep='\n\n')
x = scipy.linalg.lu_solve((lu, p), b)
print(f'x методом LU-разложения scipy:\n {x}\n')

матрица LU:
[[11.          7.          5.        ]
 [ 0.81818182  2.27272727 -0.09090909]
 [ 0.18181818 -0.12        2.08      ]]

pivot: [1 2 2]

x методом LU-разложения scipy:
 [-1.  0.  1.]

проверка x:
 [-1.  0.  1.]



In [24]:
# задача 4 метод холецкого
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

L = scipy.linalg.cho_factor(A)
x = scipy.linalg.cho_solve(L, b)
print(f'методом Холецкого x:\n {x}\n')

методом Холецкого x:
 [ 6. -5. -4.]

