In [1]:
import numpy as np
import math

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
AB_sum = A + B
print(f'Сумма матриц A и B:\n{AB_sum}\n', "_"*100)
AB_mul = A.dot(B)
print(f'Произведение матрицы A и B(метод .dot):\n{AB_mul}')
AB_mul = np.dot(A, B)
print(f'Произведение матрицы A и B(метод np.dot):\n{AB_mul}')
AB_mul = np.matmul(A, B)
print(f'Произведение матрицы A и B(метод np.matmul):\n{AB_mul}\n', "_"*100)
BA_mul = np.dot(B, A)
print(f'Произведение матрицы B и А(метод .dot):\n{BA_mul}')

Сумма матриц A и B:
[[ 5 -3]
 [ 3  5]]
 ____________________________________________________________________________________________________
Произведение матрицы A и B(метод .dot):
[[  4 -11]
 [ 12  -3]]
Произведение матрицы A и B(метод np.dot):
[[  4 -11]
 [ 12  -3]]
Произведение матрицы A и B(метод np.matmul):
[[  4 -11]
 [ 12  -3]]
 ____________________________________________________________________________________________________
Произведение матрицы B и А(метод .dot):
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [3]:
A = np.matrix([[1, 7], [3, -6]])
B = np.matrix([[0, 5], [2, -1]])
C = np.matrix([[2, -4], [1, 1]])
result = 3*A - 2*B + 4*C
print(f'Линейная комбинация 3А-2В+4С для матриц А, В, С:\n {result}')

Линейная комбинация 3А-2В+4С для матриц А, В, С:
 [[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [4]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'произведение матрицы А на транспонированную А\n{A.dot(A.T)}')
print('\n')
print(f'произведение транспонированной матрицы А на А\n{(A.T).dot(A)}')

произведение матрицы А на транспонированную А
[[17 18 11]
 [18 29  4]
 [11  4 13]]


произведение транспонированной матрицы А на А
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [5]:
# смысл был написать алгоритм перемножения матриц, а не полный отказ от numpy,
# поэтому на вход подаются матрицы numpy изключительно для нормального отображения матриц при выводе в print()
# функция будет работать и в случае подачи на вход список списков (если требование не использовать numpy в коде принципиальное)
A = np.array([[4, 1, 18], [5, -2, 4], [2, 3, 7]])
B = np.array([[4, 1, 5, 9], [5, 2, 8, 11],  [5, 12, 8, 1]])
С = np.array([[4, 1, 5], [5, 2, 8]])
print(A, B, С, sep='\n\n')

[[ 4  1 18]
 [ 5 -2  4]
 [ 2  3  7]]

[[ 4  1  5  9]
 [ 5  2  8 11]
 [ 5 12  8  1]]

[[4 1 5]
 [5 2 8]]


In [6]:
def matrix_multiplication(A, B):
    result = []
    if len(A[0]) == len(B):
        for i in range(len(A)):
            result_row = []
            for j in range(len(A[0])):
                temp_row = []
                for k in range(len(B[0])):
                    temp_row.append(A[i, j]*B[j, k])
                if not result_row:
                    result_row = temp_row
                else:
                    result_row = [x+y for x, y in zip(result_row, temp_row)]
            result.append(result_row)
        print(np.array(result))
    else:
        print(
            f"операция не может быть осуществлена т.к. число столбцов матрицы А ({len(A[0])}) не равно числу строк матрицы В ({len(B)})")

In [7]:
matrix_multiplication(A, C)

операция не может быть осуществлена т.к. число столбцов матрицы А (3) не равно числу строк матрицы В (2)


In [8]:
matrix_multiplication(A, B)

[[111 222 172  65]
 [ 30  49  41  27]
 [ 58  92  90  58]]


In [9]:
A.dot(B)  # проверка работы функции

array([[111, 222, 172,  65],
       [ 30,  49,  41,  27],
       [ 58,  92,  90,  58]])

***************************************************************************************************************************

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

In [10]:
x = 0  # любое значение
A = np.array([[math.sin(x), -math.cos(x)], [math.cos(x), math.sin(x)]])
detA = np.linalg.det(A)
detA

1.0

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

In [11]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
detA = np.linalg.det(A)
detA

180.0

    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [12]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
detA = round(np.linalg.det(A))
detA

0


__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [13]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
detA = round(np.linalg.det(A))
detA

0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [14]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
rankA = np.linalg.matrix_rank(A)
rankA

2

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [15]:
A = np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
rankA =np.linalg.matrix_rank(A)
rankA

3